import { describe, it, expect, vi, beforeEach } from "vitest";
import {
  generateAutoActions,
  executeAutoActions,
  type AutoActionContext,
  type AutoActionResult,
} from "./auto-actions";

const { mockInsertValues, mockInsert } = vi.hoisted(() => {
  const mockInsertValues = vi.fn();
  const mockInsert = vi.fn().mockReturnValue({ values: mockInsertValues });
  return { mockInsertValues, mockInsert };
});

vi.mock("@/lib/db", () => ({
  db: { insert: mockInsert },
}));

vi.mock("@/lib/db/schema", () => ({
  animalTodos: Symbol("animalTodos"),
}));

function makeContext(overrides: Partial<AutoActionContext> = {}): AutoActionContext {
  const defaults: AutoActionContext = {
    animal: {
      id: 1,
      species: "hond",
      intakeReason: "afstand",
    },
  };
  return {
    ...defaults,
    ...overrides,
    animal: { ...defaults.animal, ...overrides.animal },
  };
}

describe("generateAutoActions", () => {
  // --- AC1: intake → registratie ---

  describe("registratie phase (intake → registratie)", () => {
    it("returns 3 base tasks for a dog", () => {
      const ctx = makeContext({ animal: { id: 1, species: "hond", intakeReason: "afstand" } });
      const actions = generateAutoActions("registratie", ctx);
      expect(actions).toHaveLength(3);
      expect(actions.map((a) => a.description)).toEqual([
        "Dier registreren in overzichtsregister",
        "Kennel toewijzen",
        "Foto's uploaden",
      ]);
    });

    it("returns correct priorities for registratie tasks", () => {
      const ctx = makeContext();
      const actions = generateAutoActions("registratie", ctx);
      expect(actions[0].priority).toBe("hoog");
      expect(actions[1].priority).toBe("normaal");
      expect(actions[2].priority).toBe("laag");
    });

    it("sets deadline +2 days for 'Dier registreren' task", () => {
      const ctx = makeContext();
      const actions = generateAutoActions("registratie", ctx);
      const registerTask = actions.find((a) => a.description.includes("registreren"));
      expect(registerTask).toBeDefined();
      expect(registerTask!.dueDate).toBeDefined();
      // dueDate should be a YYYY-MM-DD string approximately 2 days from now
      const due = new Date(registerTask!.dueDate!);
      const now = new Date();
      const diffMs = due.getTime() - now.getTime();
      const diffDays = diffMs / (1000 * 60 * 60 * 24);
      expect(diffDays).toBeGreaterThanOrEqual(1);
      expect(diffDays).toBeLessThanOrEqual(3);
    });

    it("returns no deadline for 'Kennel toewijzen' and 'Foto's uploaden'", () => {
      const ctx = makeContext();
      const actions = generateAutoActions("registratie", ctx);
      const kennel = actions.find((a) => a.description.includes("Kennel"));
      const fotos = actions.find((a) => a.description.includes("Foto"));
      expect(kennel!.dueDate).toBeNull();
      expect(fotos!.dueDate).toBeNull();
    });

    it("adds IBN extra task for ibn intake reason", () => {
      const ctx = makeContext({ animal: { id: 1, species: "hond", intakeReason: "ibn" } });
      const actions = generateAutoActions("registratie", ctx);
      expect(actions).toHaveLength(4);
      const ibnTask = actions.find((a) => a.description.includes("Verwaarlozing"));
      expect(ibnTask).toBeDefined();
      expect(ibnTask!.priority).toBe("dringend");
    });

    it("does not add IBN task for non-ibn intake", () => {
      const ctx = makeContext({ animal: { id: 1, species: "hond", intakeReason: "afstand" } });
      const actions = generateAutoActions("registratie", ctx);
      expect(actions.every((a) => !a.description.includes("Verwaarlozing"))).toBe(true);
    });

    it("does not add IBN task when intakeReason is null", () => {
      const ctx = makeContext({ animal: { id: 1, species: "hond", intakeReason: null } });
      const actions = generateAutoActions("registratie", ctx);
      expect(actions).toHaveLength(3);
      expect(actions.every((a) => !a.description.includes("Verwaarlozing"))).toBe(true);
    });

    it("sets isAutoGenerated = true and workflowPhase = 'registratie' on all tasks", () => {
      const ctx = makeContext();
      const actions = generateAutoActions("registratie", ctx);
      for (const action of actions) {
        expect(action.isAutoGenerated).toBe(true);
        expect(action.workflowPhase).toBe("registratie");
      }
    });
  });

  // --- AC2: registratie → medisch ---

  describe("medisch phase (registratie → medisch)", () => {
    it("returns 4 base tasks for a dog", () => {
      const ctx = makeContext({ animal: { id: 1, species: "hond", intakeReason: "afstand" } });
      const actions = generateAutoActions("medisch", ctx);
      expect(actions).toHaveLength(4);
      expect(actions.map((a) => a.description)).toEqual([
        "Eerste onderzoek dierenarts plannen",
        "Vaccinaties toedienen",
        "Ontworming + ontvlooiing",
        "Chip controleren/plaatsen",
      ]);
    });

    it("adds sterilisatie task for cats", () => {
      const ctx = makeContext({ animal: { id: 1, species: "kat", intakeReason: "afstand" } });
      const actions = generateAutoActions("medisch", ctx);
      expect(actions).toHaveLength(5);
      const sterilisatie = actions.find((a) => a.description.includes("Sterilisatie"));
      expect(sterilisatie).toBeDefined();
      expect(sterilisatie!.priority).toBe("hoog");
    });

    it("does not add sterilisatie task for dogs", () => {
      const ctx = makeContext({ animal: { id: 1, species: "hond", intakeReason: "afstand" } });
      const actions = generateAutoActions("medisch", ctx);
      expect(actions.every((a) => !a.description.includes("Sterilisatie"))).toBe(true);
    });

    it("sets correct priorities for medisch tasks", () => {
      const ctx = makeContext({ animal: { id: 1, species: "hond", intakeReason: "afstand" } });
      const actions = generateAutoActions("medisch", ctx);
      expect(actions[0].priority).toBe("hoog"); // dierenarts
      expect(actions[1].priority).toBe("hoog"); // vaccinaties
      expect(actions[2].priority).toBe("normaal"); // ontworming
      expect(actions[3].priority).toBe("hoog"); // chip
    });

    it("sets workflowPhase = 'medisch' on all tasks", () => {
      const ctx = makeContext();
      const actions = generateAutoActions("medisch", ctx);
      for (const action of actions) {
        expect(action.workflowPhase).toBe("medisch");
      }
    });
  });

  // --- AC3: medisch → verblijf ---

  describe("verblijf phase (medisch → verblijf)", () => {
    it("returns 2 tasks for dogs (gedragsfiche + voedingsplan)", () => {
      const ctx = makeContext({ animal: { id: 1, species: "hond", intakeReason: "afstand" } });
      const actions = generateAutoActions("verblijf", ctx);
      expect(actions).toHaveLength(2);
      expect(actions.map((a) => a.description)).toEqual([
        "Gedragsfiche invullen",
        "Voedingsplan opstellen",
      ]);
    });

    it("returns only voedingsplan for cats (no gedragsfiche)", () => {
      const ctx = makeContext({ animal: { id: 1, species: "kat", intakeReason: "afstand" } });
      const actions = generateAutoActions("verblijf", ctx);
      expect(actions).toHaveLength(1);
      expect(actions[0].description).toBe("Voedingsplan opstellen");
    });

    it("sets workflowPhase = 'verblijf' on all tasks", () => {
      const ctx = makeContext();
      const actions = generateAutoActions("verblijf", ctx);
      for (const action of actions) {
        expect(action.workflowPhase).toBe("verblijf");
      }
    });
  });

  // --- AC4: adoptie → afgerond ---

  describe("afgerond phase (adoptie → afgerond)", () => {
    it("returns 3 tasks", () => {
      const ctx = makeContext();
      const actions = generateAutoActions("afgerond", ctx);
      expect(actions).toHaveLength(3);
      expect(actions.map((a) => a.description)).toEqual([
        "DogID/CatID overdracht melden",
        "Post-adoptie opvolging 1 week",
        "Post-adoptie opvolging 1 maand",
      ]);
    });

    it("sets +14 day deadline on DogID/CatID overdracht", () => {
      const ctx = makeContext();
      const actions = generateAutoActions("afgerond", ctx);
      const dogidTask = actions.find((a) => a.description.includes("DogID"));
      expect(dogidTask).toBeDefined();
      expect(dogidTask!.dueDate).toBeDefined();
      const due = new Date(dogidTask!.dueDate!);
      const now = new Date();
      const diffDays = (due.getTime() - now.getTime()) / (1000 * 60 * 60 * 24);
      expect(diffDays).toBeGreaterThanOrEqual(13);
      expect(diffDays).toBeLessThanOrEqual(15);
    });

    it("sets workflowPhase = 'afgerond' on all tasks", () => {
      const ctx = makeContext();
      const actions = generateAutoActions("afgerond", ctx);
      for (const action of actions) {
        expect(action.workflowPhase).toBe("afgerond");
      }
    });
  });

  // --- Transitions without auto-actions ---

  describe("phases without auto-actions", () => {
    it("returns empty array for intake phase", () => {
      const ctx = makeContext();
      const actions = generateAutoActions("intake", ctx);
      expect(actions).toEqual([]);
    });

    it("returns empty array for adoptie phase", () => {
      const ctx = makeContext();
      const actions = generateAutoActions("adoptie", ctx);
      expect(actions).toEqual([]);
    });

    it("returns empty array for unknown phase", () => {
      const ctx = makeContext();
      const actions = generateAutoActions("onbekend", ctx);
      expect(actions).toEqual([]);
    });
  });
});

describe("executeAutoActions", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockInsertValues.mockResolvedValue(undefined);
  });

  it("inserts auto-generated todos into database", async () => {
    const ctx = makeContext({ animal: { id: 5, species: "hond", intakeReason: "afstand" } });
    await executeAutoActions(5, "registratie", ctx, 1);
    expect(mockInsert).toHaveBeenCalled();
    expect(mockInsertValues).toHaveBeenCalledWith(
      expect.arrayContaining([
        expect.objectContaining({
          animalId: 5,
          description: "Dier registreren in overzichtsregister",
          isAutoGenerated: true,
          workflowPhase: "registratie",
          createdByUserId: 1,
        }),
      ]),
    );
  });

  it("returns descriptions and count of created actions", async () => {
    const ctx = makeContext({ animal: { id: 5, species: "hond", intakeReason: "afstand" } });
    const result = await executeAutoActions(5, "registratie", ctx, 1);
    expect(result.count).toBe(3);
    expect(result.descriptions).toHaveLength(3);
    expect(result.descriptions).toContain("Dier registreren in overzichtsregister");
  });

  it("returns count 0 for phase without auto-actions", async () => {
    const ctx = makeContext();
    const result = await executeAutoActions(1, "intake", ctx, 1);
    expect(result.count).toBe(0);
    expect(result.descriptions).toEqual([]);
    expect(mockInsert).not.toHaveBeenCalled();
  });

  it("inserts IBN task for ibn animals", async () => {
    const ctx = makeContext({ animal: { id: 5, species: "hond", intakeReason: "ibn" } });
    const result = await executeAutoActions(5, "registratie", ctx, 1);
    expect(result.count).toBe(4);
    expect(result.descriptions).toContain("Verwaarlozing-rapport opstellen");
  });

  it("includes species-specific tasks (cat sterilisatie in medisch)", async () => {
    const ctx = makeContext({ animal: { id: 5, species: "kat", intakeReason: "afstand" } });
    const result = await executeAutoActions(5, "medisch", ctx, 1);
    expect(result.count).toBe(5);
    expect(result.descriptions).toContain("Sterilisatie plannen");
  });

  it("returns count 0 and does not throw on db error", async () => {
    mockInsertValues.mockRejectedValue(new Error("DB error"));
    const ctx = makeContext();
    const result = await executeAutoActions(1, "registratie", ctx, 1);
    expect(result.count).toBe(0);
    expect(result.descriptions).toEqual([]);
  });

  it("sets correct priority on inserted records", async () => {
    const ctx = makeContext({ animal: { id: 5, species: "hond", intakeReason: "afstand" } });
    await executeAutoActions(5, "registratie", ctx, 1);
    const insertedValues = mockInsertValues.mock.calls[0][0];
    expect(insertedValues[0].priority).toBe("hoog");
    expect(insertedValues[1].priority).toBe("normaal");
    expect(insertedValues[2].priority).toBe("laag");
  });

  it("passes dueDate from generated actions to insert", async () => {
    const ctx = makeContext({ animal: { id: 5, species: "hond", intakeReason: "afstand" } });
    await executeAutoActions(5, "registratie", ctx, 1);
    const insertedValues = mockInsertValues.mock.calls[0][0];
    expect(insertedValues[0].dueDate).toBeDefined(); // registreren has +48h
    expect(insertedValues[1].dueDate).toBeNull(); // kennel has no deadline
  });
});
