import { db } from "@/lib/db";
import { animalTodos } from "@/lib/db/schema";

export interface AutoActionContext {
  animal: {
    id: number;
    species: string;
    intakeReason: string | null;
  };
}

export interface AutoActionResult {
  type: string;
  description: string;
  priority: "dringend" | "hoog" | "normaal" | "laag";
  dueDate: string | null;
  isAutoGenerated: true;
  workflowPhase: string;
}

interface AutoActionTemplate {
  type: string;
  description: string;
  priority: "dringend" | "hoog" | "normaal" | "laag";
  deadlineDays?: number;
  deadlineHours?: number;
  condition?: (ctx: AutoActionContext) => boolean;
}

function calculateDueDate(template: AutoActionTemplate): string | null {
  if (!template.deadlineDays && !template.deadlineHours) return null;
  const due = new Date();
  if (template.deadlineHours) {
    due.setHours(due.getHours() + template.deadlineHours);
  }
  if (template.deadlineDays) {
    due.setDate(due.getDate() + template.deadlineDays);
  }
  return `${due.getFullYear()}-${String(due.getMonth() + 1).padStart(2, "0")}-${String(due.getDate()).padStart(2, "0")}`;
}

const PHASE_AUTO_ACTIONS: Record<string, AutoActionTemplate[]> = {
  registratie: [
    { type: "administratief", description: "Dier registreren in overzichtsregister", priority: "hoog", deadlineHours: 48 },
    { type: "huisvesting", description: "Kennel toewijzen", priority: "normaal" },
    { type: "administratief", description: "Foto's uploaden", priority: "laag" },
    {
      type: "juridisch", description: "Verwaarlozing-rapport opstellen", priority: "dringend",
      condition: (ctx) => ctx.animal.intakeReason === "ibn",
    },
  ],
  medisch: [
    { type: "medisch", description: "Eerste onderzoek dierenarts plannen", priority: "hoog" },
    { type: "medisch", description: "Vaccinaties toedienen", priority: "hoog" },
    { type: "medisch", description: "Ontworming + ontvlooiing", priority: "normaal" },
    { type: "medisch", description: "Chip controleren/plaatsen", priority: "hoog" },
    {
      type: "medisch", description: "Sterilisatie plannen", priority: "hoog",
      condition: (ctx) => ctx.animal.species === "kat",
    },
  ],
  verblijf: [
    {
      type: "gedrag", description: "Gedragsfiche invullen", priority: "normaal",
      condition: (ctx) => ctx.animal.species === "hond",
    },
    { type: "voeding", description: "Voedingsplan opstellen", priority: "normaal" },
  ],
  afgerond: [
    { type: "administratief", description: "DogID/CatID overdracht melden", priority: "hoog", deadlineDays: 14 },
    { type: "opvolging", description: "Post-adoptie opvolging 1 week", priority: "normaal" },
    { type: "opvolging", description: "Post-adoptie opvolging 1 maand", priority: "normaal" },
  ],
};

/**
 * Generate auto-action results for a given target phase.
 * Pure function: evaluates templates against context, calculates deadlines.
 * Returns filtered and populated action list (empty if no actions for this phase).
 */
export function generateAutoActions(
  toPhase: string,
  context: AutoActionContext,
): AutoActionResult[] {
  const templates = PHASE_AUTO_ACTIONS[toPhase];
  if (!templates) return [];

  return templates
    .filter((t) => !t.condition || t.condition(context))
    .map((t) => ({
      type: t.type,
      description: t.description,
      priority: t.priority,
      dueDate: calculateDueDate(t),
      isAutoGenerated: true as const,
      workflowPhase: toPhase,
    }));
}

export interface ExecuteAutoActionsResult {
  count: number;
  descriptions: string[];
}

/**
 * Execute auto-actions: generate and insert todos for a phase transition.
 * Fire-and-forget: DB errors are caught and logged, never fail the caller.
 */
export async function executeAutoActions(
  animalId: number,
  toPhase: string,
  context: AutoActionContext,
  userId: number,
): Promise<ExecuteAutoActionsResult> {
  const actions = generateAutoActions(toPhase, context);
  if (actions.length === 0) {
    return { count: 0, descriptions: [] };
  }

  try {
    await db.insert(animalTodos).values(
      actions.map((a) => ({
        animalId,
        type: a.type,
        description: a.description,
        priority: a.priority,
        dueDate: a.dueDate,
        isAutoGenerated: true,
        workflowPhase: a.workflowPhase,
        createdByUserId: userId,
      })),
    );
    return { count: actions.length, descriptions: actions.map((a) => a.description) };
  } catch (err) {
    console.error("executeAutoActions failed:", err);
    return { count: 0, descriptions: [] };
  }
}
