import { describe, it, expect } from "vitest";
import {
  getPhaseStatus,
  PHASE_LABELS,
  groupOpenTodosByPhase,
} from "./stepbar";

describe("getPhaseStatus", () => {
  it("returns 'completed' for phases before the current phase", () => {
    expect(getPhaseStatus("medisch", "intake")).toBe("completed");
    expect(getPhaseStatus("medisch", "registratie")).toBe("completed");
  });

  it("returns 'active' for the current phase", () => {
    expect(getPhaseStatus("medisch", "medisch")).toBe("active");
    expect(getPhaseStatus("intake", "intake")).toBe("active");
    expect(getPhaseStatus("afgerond", "afgerond")).toBe("active");
  });

  it("returns 'future' for phases after the current phase", () => {
    expect(getPhaseStatus("medisch", "verblijf")).toBe("future");
    expect(getPhaseStatus("medisch", "adoptie")).toBe("future");
    expect(getPhaseStatus("medisch", "afgerond")).toBe("future");
  });

  it("returns 'future' for unknown current phase", () => {
    expect(getPhaseStatus("onbekend", "intake")).toBe("future");
  });

  it("returns 'future' for unknown target phase", () => {
    expect(getPhaseStatus("medisch", "onbekend")).toBe("future");
  });
});

describe("PHASE_LABELS", () => {
  it("has labels for all 6 workflow phases", () => {
    expect(Object.keys(PHASE_LABELS)).toHaveLength(6);
    expect(PHASE_LABELS.intake).toBe("Intake");
    expect(PHASE_LABELS.registratie).toBe("Registratie");
    expect(PHASE_LABELS.medisch).toBe("Medisch");
    expect(PHASE_LABELS.verblijf).toBe("Verblijf");
    expect(PHASE_LABELS.adoptie).toBe("Adoptie");
    expect(PHASE_LABELS.afgerond).toBe("Afgerond");
  });
});

describe("groupOpenTodosByPhase", () => {
  const makeTodo = (overrides: Record<string, unknown> = {}) => ({
    id: 1,
    animalId: 5,
    type: "administratief",
    description: "Test taak",
    isCompleted: false,
    completedAt: null,
    completedByUserId: null,
    dueDate: null,
    isAutoGenerated: true,
    workflowPhase: "registratie",
    priority: "normaal",
    createdByUserId: null,
    createdAt: new Date(),
    ...overrides,
  });

  it("groups open todos by workflowPhase", () => {
    const todos = [
      makeTodo({ id: 1, workflowPhase: "registratie" }),
      makeTodo({ id: 2, workflowPhase: "registratie" }),
      makeTodo({ id: 3, workflowPhase: "medisch" }),
    ];
    const grouped = groupOpenTodosByPhase(todos);
    expect(grouped.registratie).toHaveLength(2);
    expect(grouped.medisch).toHaveLength(1);
  });

  it("excludes completed todos", () => {
    const todos = [
      makeTodo({ id: 1, workflowPhase: "registratie", isCompleted: false }),
      makeTodo({ id: 2, workflowPhase: "registratie", isCompleted: true }),
    ];
    const grouped = groupOpenTodosByPhase(todos);
    expect(grouped.registratie).toHaveLength(1);
    expect(grouped.registratie[0].id).toBe(1);
  });

  it("returns empty object for empty todo list", () => {
    const grouped = groupOpenTodosByPhase([]);
    expect(Object.keys(grouped)).toHaveLength(0);
  });

  it("ignores todos without workflowPhase", () => {
    const todos = [
      makeTodo({ id: 1, workflowPhase: null }),
      makeTodo({ id: 2, workflowPhase: "medisch" }),
    ];
    const grouped = groupOpenTodosByPhase(todos);
    expect(grouped.medisch).toHaveLength(1);
    expect(grouped["null"]).toBeUndefined();
  });
});
