"use server";

import { db } from "@/lib/db";
import { adoptionContracts, adoptionCandidates, animals, animalTodos, postAdoptionFollowups } from "@/lib/db/schema";
import { eq, and } from "drizzle-orm";
import { requirePermission } from "@/lib/permissions";
import { logAudit } from "@/lib/audit";
import { adoptionContractSchema } from "@/lib/validations/adoption-contracts";
import { getAnimalById } from "@/lib/queries/animals";
import { getVaccinationsByAnimalId } from "@/lib/queries/vaccinations";
import { getSession } from "@/lib/auth/session";
import { revalidatePath } from "next/cache";
import type { ActionResult, AdoptionContract } from "@/types";

function addDays(dateStr: string, days: number): string {
  const d = new Date(dateStr);
  d.setDate(d.getDate() + days);
  return d.toISOString().split("T")[0];
}

export async function createAdoptionContract(
  _prevState: ActionResult<AdoptionContract> | null,
  formData: FormData,
): Promise<ActionResult<AdoptionContract>> {
  const permCheck = await requirePermission("adoption:write");
  if (permCheck && !permCheck.success) {
    return { success: false, error: permCheck.error };
  }

  let raw: unknown;
  try {
    raw = JSON.parse(formData.get("json") as string);
  } catch {
    return { success: false, error: "Ongeldige gegevens" };
  }

  const parsed = adoptionContractSchema.safeParse(raw);
  if (!parsed.success) {
    return { success: false, fieldErrors: parsed.error.flatten().fieldErrors };
  }

  // Check candidate exists and is approved
  let candidate;
  try {
    const [found] = await db
      .select()
      .from(adoptionCandidates)
      .where(eq(adoptionCandidates.id, parsed.data.candidateId))
      .limit(1);
    if (!found) return { success: false, error: "Kandidaat niet gevonden" };
    if (found.status !== "approved") {
      return { success: false, error: "Alleen een goedgekeurde kandidaat kan een contract krijgen" };
    }
    candidate = found;
  } catch {
    return { success: false, error: "Fout bij ophalen kandidaat" };
  }

  // Check animal exists
  const animal = await getAnimalById(parsed.data.animalId);
  if (!animal) return { success: false, error: "Dier niet gevonden" };

  // AC2: Kattenvalidatie (FR-02, SC-5)
  if (animal.species === "kat") {
    const errors: string[] = [];
    if (!animal.identificationNr) errors.push("gechipt");
    const vaccinations = await getVaccinationsByAnimalId(animal.id);
    if (vaccinations.length === 0) errors.push("gevaccineerd");
    if (!animal.isNeutered) errors.push("gesteriliseerd");
    if (errors.length > 0) {
      return {
        success: false,
        error: `Katten moeten ${errors.join(", ")} zijn vóór adoptie`,
      };
    }
  }

  // AC3: Chipwaarschuwing voor niet-katten
  let warning: string | undefined;
  if (animal.species !== "kat" && !animal.identificationNr) {
    warning = "Chipregistratie ontbreekt — wettelijk verplicht bij adoptie";
  }

  // AC4: Deadline berekening
  const deadline = addDays(parsed.data.contractDate, 14);

  try {
    const [record] = await db
      .insert(adoptionContracts)
      .values({
        animalId: parsed.data.animalId,
        candidateId: parsed.data.candidateId,
        contractDate: parsed.data.contractDate,
        paymentAmount: parsed.data.paymentAmount,
        paymentMethod: parsed.data.paymentMethod,
        dogidCatidTransferDeadline: deadline,
        dogidCatidTransferred: false,
        notes: parsed.data.notes || null,
      })
      .returning();

    // AC5: Update candidate status to adopted
    await db
      .update(adoptionCandidates)
      .set({ status: "adopted" })
      .where(eq(adoptionCandidates.id, candidate.id));

    // AC5: Update animal
    await db
      .update(animals)
      .set({
        status: "geadopteerd",
        isInShelter: false,
        outtakeDate: parsed.data.contractDate,
        outtakeReason: "adoptie",
      })
      .where(eq(animals.id, animal.id));

    // Story 4.5 AC1: Auto-create DogID/CatID overdracht todo (non-critical)
    try {
      await db.insert(animalTodos).values({
        animalId: parsed.data.animalId,
        type: "dogid_catid_overdracht",
        description: `DogID/CatID overdracht melden voor ${animal.name} (deadline: ${deadline})`,
        dueDate: deadline,
        priority: "hoog",
        isAutoGenerated: true,
      });
    } catch (err) {
      console.error("Auto-todo creation failed (non-critical):", err);
    }

    // Story 4.6 AC2: Auto-create post-adoption followups (non-critical)
    try {
      await db.insert(postAdoptionFollowups).values([
        { contractId: record.id, followupType: "1_week", date: addDays(parsed.data.contractDate, 7), status: "planned" },
        { contractId: record.id, followupType: "1_month", date: addDays(parsed.data.contractDate, 30), status: "planned" },
      ]);
    } catch (err) {
      console.error("Auto-followup creation failed (non-critical):", err);
    }

    await logAudit("create_adoption_contract", "adoption_contract", record.id, null, record);
    revalidatePath("/beheerder/adoptie");

    return { success: true, data: record as AdoptionContract, message: warning };
  } catch {
    return {
      success: false,
      error: "Er ging iets mis bij het opslaan. Probeer het later opnieuw.",
    };
  }
}

// Story 4.5 AC2: Mark DogID/CatID transfer as completed
export async function markDogidCatidTransferred(
  _prevState: ActionResult | null,
  formData: FormData,
): Promise<ActionResult> {
  const permCheck = await requirePermission("adoption:write");
  if (permCheck && !permCheck.success) {
    return { success: false, error: permCheck.error };
  }

  const contractId = Number(formData.get("contractId"));
  if (!contractId || isNaN(contractId)) {
    return { success: false, error: "Ongeldig contract ID" };
  }

  try {
    // Find contract
    const [contract] = await db
      .select()
      .from(adoptionContracts)
      .where(eq(adoptionContracts.id, contractId))
      .limit(1);
    if (!contract) return { success: false, error: "Contract niet gevonden" };
    if (contract.dogidCatidTransferred) {
      return { success: false, error: "DogID/CatID overdracht is reeds geregistreerd" };
    }

    // Update contract
    await db
      .update(adoptionContracts)
      .set({ dogidCatidTransferred: true })
      .where(eq(adoptionContracts.id, contractId));

    // Complete the related auto-generated todo
    const session = await getSession();
    const [todo] = await db
      .select()
      .from(animalTodos)
      .where(
        and(
          eq(animalTodos.animalId, contract.animalId),
          eq(animalTodos.type, "dogid_catid_overdracht"),
        ),
      )
      .limit(1);

    if (todo && !todo.isCompleted) {
      await db
        .update(animalTodos)
        .set({
          isCompleted: true,
          completedAt: new Date(),
          completedByUserId: session?.userId ?? null,
        })
        .where(eq(animalTodos.id, todo.id));
    }

    await logAudit(
      "mark_dogid_catid_transferred",
      "adoption_contract",
      contract.id,
      { dogidCatidTransferred: false },
      { dogidCatidTransferred: true },
    );

    revalidatePath("/beheerder/adoptie");
    revalidatePath("/beheerder/dieren");
    revalidatePath("/beheerder/dieren/[id]", "page");
    revalidatePath("/beheerder");

    return { success: true, data: undefined };
  } catch {
    return {
      success: false,
      error: "Er ging iets mis. Probeer het later opnieuw.",
    };
  }
}
