import { describe, it, expect, vi, beforeEach } from "vitest";

const {
  mockReturning, mockInsert,
  mockUpdateReturning, mockUpdateWhere, mockUpdateSet, mockUpdate,
  mockDeleteWhere, mockDelete,
  mockSelectLimit, mockSelectWhere, mockSelectFrom,
  mockRequirePermission, mockLogAudit, mockRevalidatePath, mockGetSession,
  mockGetAnimalById,
} = vi.hoisted(() => {
  const mockReturning = vi.fn();
  const mockInsert = vi.fn();
  const mockUpdateReturning = vi.fn();
  const mockUpdateWhere = vi.fn().mockReturnValue({ returning: mockUpdateReturning });
  const mockUpdateSet = vi.fn().mockReturnValue({ where: mockUpdateWhere });
  const mockUpdate = vi.fn().mockReturnValue({ set: mockUpdateSet });
  const mockDeleteWhere = vi.fn();
  const mockDelete = vi.fn().mockReturnValue({ where: mockDeleteWhere });
  const mockSelectLimit = vi.fn();
  const mockSelectWhere = vi.fn().mockReturnValue({ limit: mockSelectLimit });
  const mockSelectFrom = vi.fn().mockReturnValue({ where: mockSelectWhere });
  const mockRequirePermission = vi.fn();
  const mockLogAudit = vi.fn();
  const mockRevalidatePath = vi.fn();
  const mockGetSession = vi.fn();
  const mockGetAnimalById = vi.fn();
  return {
    mockReturning, mockInsert,
    mockUpdateReturning, mockUpdateWhere, mockUpdateSet, mockUpdate,
    mockDeleteWhere, mockDelete,
    mockSelectLimit, mockSelectWhere, mockSelectFrom,
    mockRequirePermission, mockLogAudit, mockRevalidatePath, mockGetSession,
    mockGetAnimalById,
  };
});

vi.mock("@/lib/db", () => {
  const mockValuesChain = vi.fn().mockReturnValue({ returning: mockReturning });
  mockInsert.mockReturnValue({ values: mockValuesChain });
  return {
    db: {
      insert: mockInsert,
      update: mockUpdate,
      delete: mockDelete,
      select: vi.fn().mockReturnValue({ from: mockSelectFrom }),
    },
  };
});

vi.mock("next/cache", () => ({ revalidatePath: mockRevalidatePath }));
vi.mock("@/lib/db/schema", () => ({
  animalTodos: { id: Symbol("animalTodos.id") },
}));
vi.mock("@/lib/permissions", () => ({ requirePermission: mockRequirePermission }));
vi.mock("@/lib/audit", () => ({ logAudit: mockLogAudit }));
vi.mock("@/lib/auth/session", () => ({ getSession: mockGetSession }));
vi.mock("@/lib/queries/animals", () => ({ getAnimalById: mockGetAnimalById }));
vi.mock("drizzle-orm", () => ({
  eq: vi.fn((...args: unknown[]) => ({ type: "eq", args })),
  and: vi.fn((...args: unknown[]) => ({ type: "and", args })),
}));

import { createAnimalTodo, completeAnimalTodo, deleteAnimalTodo } from "./animal-todos";

function makeFormData(data: Record<string, string>): FormData {
  const fd = new FormData();
  for (const [key, value] of Object.entries(data)) fd.append(key, value);
  return fd;
}

const createdTodo = {
  id: 1, animalId: 10, type: "vaccinatie", description: "Eerste vaccinatie",
  isCompleted: false, completedAt: null, completedByUserId: null,
  dueDate: "2026-03-15", isAutoGenerated: false, workflowPhase: null,
  priority: "normaal", createdByUserId: 3, createdAt: new Date("2026-02-26T10:00:00Z"),
};

const existingAnimal = { id: 10, name: "Rex", species: "hond" };

describe("createAnimalTodo", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockRequirePermission.mockResolvedValue(undefined);
    mockLogAudit.mockResolvedValue(undefined);
    mockGetSession.mockResolvedValue({ userId: 3, name: "Jan Peeters", role: "medewerker" });
    mockGetAnimalById.mockResolvedValue(existingAnimal);
    mockReturning.mockResolvedValue([createdTodo]);
  });

  it("requires animal:write permission", async () => {
    mockRequirePermission.mockResolvedValue({ success: false, error: "Onvoldoende rechten" });
    const result = await createAnimalTodo(null, makeFormData({
      animalId: "10", type: "vaccinatie", description: "Test",
    }));
    expect(mockRequirePermission).toHaveBeenCalledWith("animal:write");
    expect(result.success).toBe(false);
    if (!result.success) expect(result.error).toBe("Onvoldoende rechten");
  });

  it("returns fieldErrors when animalId is invalid", async () => {
    const result = await createAnimalTodo(null, makeFormData({
      animalId: "0", type: "vaccinatie", description: "Test",
    }));
    expect(result.success).toBe(false);
    if (!result.success) expect(result.fieldErrors?.animalId).toBeDefined();
  });

  it("returns fieldErrors when type is invalid", async () => {
    const result = await createAnimalTodo(null, makeFormData({
      animalId: "10", type: "onbekend", description: "Test",
    }));
    expect(result.success).toBe(false);
    if (!result.success) expect(result.fieldErrors?.type).toBeDefined();
  });

  it("returns fieldErrors when description is empty", async () => {
    const result = await createAnimalTodo(null, makeFormData({
      animalId: "10", type: "vaccinatie", description: "",
    }));
    expect(result.success).toBe(false);
    if (!result.success) expect(result.fieldErrors?.description).toBeDefined();
  });

  it("returns error when animal does not exist", async () => {
    mockGetAnimalById.mockResolvedValue(null);
    const result = await createAnimalTodo(null, makeFormData({
      animalId: "10", type: "vaccinatie", description: "Test",
    }));
    expect(result.success).toBe(false);
    if (!result.success) expect(result.error).toBe("Dier niet gevonden");
  });

  it("creates todo successfully", async () => {
    const result = await createAnimalTodo(null, makeFormData({
      animalId: "10", type: "vaccinatie", description: "Eerste vaccinatie",
    }));
    expect(result.success).toBe(true);
    expect(mockInsert).toHaveBeenCalled();
  });

  it("stores optional dueDate and priority", async () => {
    const result = await createAnimalTodo(null, makeFormData({
      animalId: "10", type: "vaccinatie", description: "Test",
      dueDate: "2026-03-15", priority: "hoog",
    }));
    expect(result.success).toBe(true);
  });

  it("calls logAudit after success", async () => {
    await createAnimalTodo(null, makeFormData({
      animalId: "10", type: "vaccinatie", description: "Test",
    }));
    expect(mockLogAudit).toHaveBeenCalledWith(
      "create_animal_todo", "animal_todo", 1, null, expect.objectContaining({ id: 1 }),
    );
  });

  it("revalidates correct paths", async () => {
    await createAnimalTodo(null, makeFormData({
      animalId: "10", type: "vaccinatie", description: "Test",
    }));
    expect(mockRevalidatePath).toHaveBeenCalledWith("/beheerder/dieren");
    expect(mockRevalidatePath).toHaveBeenCalledWith("/beheerder/dieren/[id]", "page");
    expect(mockRevalidatePath).toHaveBeenCalledWith("/beheerder");
  });

  it("stores null createdByUserId when session is null", async () => {
    mockGetSession.mockResolvedValue(null);
    const result = await createAnimalTodo(null, makeFormData({
      animalId: "10", type: "vaccinatie", description: "Test",
    }));
    expect(result.success).toBe(true);
  });

  it("returns graceful error on DB failure", async () => {
    mockReturning.mockRejectedValue(new Error("Connection refused"));
    const result = await createAnimalTodo(null, makeFormData({
      animalId: "10", type: "vaccinatie", description: "Test",
    }));
    expect(result.success).toBe(false);
    if (!result.success) expect(result.error).toBeDefined();
  });
});

const completedTodo = {
  ...createdTodo,
  isCompleted: true,
  completedAt: new Date("2026-02-26T12:00:00Z"),
  completedByUserId: 3,
};

describe("completeAnimalTodo", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockRequirePermission.mockResolvedValue(undefined);
    mockLogAudit.mockResolvedValue(undefined);
    mockGetSession.mockResolvedValue({ userId: 3, name: "Jan Peeters", role: "medewerker" });
    mockSelectLimit.mockResolvedValue([createdTodo]);
    mockUpdateReturning.mockResolvedValue([completedTodo]);
  });

  it("requires animal:write permission", async () => {
    mockRequirePermission.mockResolvedValue({ success: false, error: "Onvoldoende rechten" });
    const result = await completeAnimalTodo(null, makeFormData({ id: "1" }));
    expect(mockRequirePermission).toHaveBeenCalledWith("animal:write");
    expect(result.success).toBe(false);
  });

  it("returns error when id is invalid", async () => {
    const result = await completeAnimalTodo(null, makeFormData({ id: "abc" }));
    expect(result.success).toBe(false);
    if (!result.success) expect(result.error).toBe("Ongeldig ID");
  });

  it("returns error when not found", async () => {
    mockSelectLimit.mockResolvedValue([]);
    const result = await completeAnimalTodo(null, makeFormData({ id: "999" }));
    expect(result.success).toBe(false);
    if (!result.success) expect(result.error).toBe("Taak niet gevonden");
  });

  it("returns error when already completed", async () => {
    mockSelectLimit.mockResolvedValue([{ ...createdTodo, isCompleted: true }]);
    const result = await completeAnimalTodo(null, makeFormData({ id: "1" }));
    expect(result.success).toBe(false);
    if (!result.success) expect(result.error).toBe("Taak is al afgerond");
  });

  it("completes todo successfully", async () => {
    const result = await completeAnimalTodo(null, makeFormData({ id: "1" }));
    expect(result.success).toBe(true);
    expect(mockUpdate).toHaveBeenCalled();
  });

  it("returns error when conditional update matches nothing (race condition)", async () => {
    mockUpdateReturning.mockResolvedValue([]);
    const result = await completeAnimalTodo(null, makeFormData({ id: "1" }));
    expect(result.success).toBe(false);
    if (!result.success) expect(result.error).toBe("Taak is al afgerond");
  });

  it("calls logAudit with old and new value", async () => {
    await completeAnimalTodo(null, makeFormData({ id: "1" }));
    expect(mockLogAudit).toHaveBeenCalledWith(
      "complete_animal_todo", "animal_todo", 1,
      expect.objectContaining({ isCompleted: false }),
      expect.objectContaining({ isCompleted: true }),
    );
  });

  it("revalidates correct paths", async () => {
    await completeAnimalTodo(null, makeFormData({ id: "1" }));
    expect(mockRevalidatePath).toHaveBeenCalledWith("/beheerder/dieren");
    expect(mockRevalidatePath).toHaveBeenCalledWith("/beheerder/dieren/[id]", "page");
    expect(mockRevalidatePath).toHaveBeenCalledWith("/beheerder");
  });

  it("returns graceful error on DB failure", async () => {
    mockUpdateReturning.mockRejectedValue(new Error("Connection refused"));
    const result = await completeAnimalTodo(null, makeFormData({ id: "1" }));
    expect(result.success).toBe(false);
  });
});

describe("deleteAnimalTodo", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    mockRequirePermission.mockResolvedValue(undefined);
    mockLogAudit.mockResolvedValue(undefined);
    mockSelectLimit.mockResolvedValue([createdTodo]);
    mockDeleteWhere.mockResolvedValue(undefined);
  });

  it("requires animal:write permission", async () => {
    mockRequirePermission.mockResolvedValue({ success: false, error: "Onvoldoende rechten" });
    const result = await deleteAnimalTodo(null, makeFormData({ id: "1" }));
    expect(mockRequirePermission).toHaveBeenCalledWith("animal:write");
    expect(result.success).toBe(false);
  });

  it("returns error when id is invalid", async () => {
    const result = await deleteAnimalTodo(null, makeFormData({ id: "abc" }));
    expect(result.success).toBe(false);
    if (!result.success) expect(result.error).toBe("Ongeldig ID");
  });

  it("returns error when not found", async () => {
    mockSelectLimit.mockResolvedValue([]);
    const result = await deleteAnimalTodo(null, makeFormData({ id: "999" }));
    expect(result.success).toBe(false);
    if (!result.success) expect(result.error).toBe("Taak niet gevonden");
  });

  it("deletes successfully", async () => {
    const result = await deleteAnimalTodo(null, makeFormData({ id: "1" }));
    expect(result.success).toBe(true);
    expect(mockDelete).toHaveBeenCalled();
  });

  it("calls logAudit with old value", async () => {
    await deleteAnimalTodo(null, makeFormData({ id: "1" }));
    expect(mockLogAudit).toHaveBeenCalledWith(
      "delete_animal_todo", "animal_todo", 1, createdTodo, null,
    );
  });

  it("revalidates correct paths", async () => {
    await deleteAnimalTodo(null, makeFormData({ id: "1" }));
    expect(mockRevalidatePath).toHaveBeenCalledWith("/beheerder/dieren");
    expect(mockRevalidatePath).toHaveBeenCalledWith("/beheerder/dieren/[id]", "page");
    expect(mockRevalidatePath).toHaveBeenCalledWith("/beheerder");
  });

  it("returns graceful error on DB failure", async () => {
    mockDeleteWhere.mockRejectedValue(new Error("Connection refused"));
    const result = await deleteAnimalTodo(null, makeFormData({ id: "1" }));
    expect(result.success).toBe(false);
  });
});
