import type { NewAnimal } from "@/types";

export const dogSeeds: NewAnimal[] = [
  {
    name: "Aira",
    slug: "aira",
    species: "hond",
    breed: "Terrier Mix",
    gender: "reu",
    dateOfBirth: "2015-03-15",
    isNeutered: true,
    description:
      "Officieel ben ik een oudere heer, maar noem mij gerust een jonge kerel. Ik ben Aira, een terrier mix met een hart van goud. Ondanks mijn leeftijd zit ik nog vol energie en ben ik altijd in voor een stevige wandeling of een gezellig spel. Ik ben op zoek naar een rustig huisje waar ik mijn oude dag kan doorbrengen met een baasje dat van mij houdt.",
    shortDescription: "Een lieve terrier mix die nog vol energie zit ondanks zijn leeftijd.",
    imageUrl: "https://placedog.net/500/400?id=1",
    status: "beschikbaar",
    isFeatured: true,
    intakeDate: "2024-06-01",
  },
  {
    name: "Athena",
    slug: "athena",
    species: "hond",
    breed: "Mechelse Herder",
    gender: "teef",
    dateOfBirth: "2022-03-09",
    isNeutered: false,
    description:
      "Ik ben een prachtige, compacte Mechelse herder van 3,5 jaar jong. Athena is mijn naam en ik ben even mooi als de godin naar wie ik vernoemd ben. Ik ben een actieve hond die nood heeft aan een ervaren baasje dat mij de structuur en de liefde kan geven die ik verdien. Ik ben intelligent, leergierig en wil niets liever dan mijn baasje trots maken.",
    shortDescription: "Een prachtige, compacte Mechelse herder van 3,5 jaar jong.",
    imageUrl: "https://placedog.net/500/400?id=2",
    status: "beschikbaar",
    isFeatured: true,
    intakeDate: "2024-09-01",
  },
  {
    name: "Bella",
    slug: "bella",
    species: "hond",
    breed: "Siberische Husky",
    gender: "teef",
    dateOfBirth: "2020-12-29",
    isNeutered: true,
    description:
      "En ja hoor, mijn naam zegt het al: ik ben mooi. Ik ben Bella, een prachtige Siberische Husky met de mooiste blauwe ogen die je ooit gezien hebt. Ik ben gesteriliseerd en klaar om een nieuw avontuur te beginnen. Ik hou van lange wandelingen, in de sneeuw spelen en knuffelen op de bank. Ik zoek een actief gezin dat mij de ruimte en beweging kan geven die ik nodig heb.",
    shortDescription: "Een prachtige Siberische Husky met de mooiste blauwe ogen.",
    imageUrl: "https://placedog.net/500/400?id=3",
    status: "beschikbaar",
    isFeatured: true,
    intakeDate: "2024-03-15",
  },
  {
    name: "Boy",
    slug: "boy",
    species: "hond",
    breed: "Engelse Pointer",
    gender: "reu",
    dateOfBirth: "2023-10-01",
    isNeutered: true,
    description:
      "Ik ben een jonge Engelse Pointer en ben via een inbeslagname in het asiel terechtgekomen. Boy is mijn naam en ik ben een echte gentleman. Ik ben gecastreerd, sociaal met andere honden en vol levenslust. Ik zoek een sportief baasje dat mij meeneemt op lange wandelingen en avonturen. Met de juiste begeleiding word ik de beste vriend die je je kan wensen.",
    shortDescription: "Een jonge Engelse Pointer vol levenslust en avontuur.",
    imageUrl: "https://placedog.net/500/400?id=4",
    status: "beschikbaar",
    badge: "nieuw",
    isFeatured: true,
    intakeDate: "2025-01-10",
  },
  {
    name: "Iza",
    slug: "iza",
    species: "hond",
    breed: "American Staffordshire Terrier",
    gender: "teef",
    dateOfBirth: "2023-05-23",
    isNeutered: false,
    description:
      "Een jonge, lieve Stafford met een groot hart, een nog grotere knuffelnood en de liefste ogen die je ooit gezien hebt. Iza is mijn naam en ik wil niets liever dan bij mijn baasje op de bank liggen en geknuffeld worden. Ik ben vriendelijk, speels en altijd in voor een wandeling. Geef mij een kans en ik beloof je dat ik je leven zal verrijken met onvoorwaardelijke liefde.",
    shortDescription: "Een jonge, lieve Stafford met een groot hart en een nog grotere knuffelnood.",
    imageUrl: "https://placedog.net/500/400?id=5",
    status: "beschikbaar",
    isFeatured: true,
    intakeDate: "2024-11-01",
  },
  {
    name: "Kamiel",
    slug: "kamiel",
    species: "hond",
    breed: "American Staffordshire Terrier",
    gender: "reu",
    dateOfBirth: "2021-06-01",
    isNeutered: true,
    description:
      "Ik ben in de opvang beland via de politie. Kamiel is mijn naam en ik ben een stevige American Stafford die op zoek is naar een ervaren baasje. Ik ben gecastreerd en heb een goed karakter, maar ik heb wel een baasje nodig dat mij begrijpt en mij de leiding geeft die ik nodig heb. Met de juiste begeleiding ben ik een trouwe en liefdevolle metgezel.",
    shortDescription: "Een stevige American Stafford op zoek naar een ervaren baasje.",
    imageUrl: "https://placedog.net/500/400?id=6",
    status: "beschikbaar",
    intakeDate: "2024-07-15",
  },
  {
    name: "Lex",
    slug: "lex",
    species: "hond",
    breed: "Siberische Husky",
    gender: "reu",
    dateOfBirth: "2020-09-15",
    isNeutered: true,
    description:
      "Een prachtige witte Husky, alsof ik recht uit een sneeuwlandschap ben gestapt. Lex is mijn naam en ik ben een echte schoonheid. Ik ben gecastreerd en klaar voor een nieuw leven. Ik hou van wandelen, rennen en spelen. Ik zoek een actief gezin met ervaring met Husky's die mij de beweging en aandacht kan geven die ik verdien.",
    shortDescription: "Een prachtige witte Husky, alsof hij recht uit een sneeuwlandschap komt.",
    imageUrl: "https://placedog.net/500/400?id=7",
    status: "beschikbaar",
    intakeDate: "2024-05-01",
  },
  {
    name: "Miro",
    slug: "miro",
    species: "hond",
    breed: "Chihuahua",
    gender: "reu",
    dateOfBirth: "2014-12-07",
    isNeutered: false,
    description:
      "De eerste keer dat ik in de opvang terechtkwam, was door inbeslagname. Miro is mijn naam en ik ben een kleine Chihuahua met een groot karakter. Ondanks mijn leeftijd ben ik nog steeds een kwieke kerel die geniet van wandelingetjes en gezelligheid. Ik zoek een rustig huisje waar ik verwend kan worden in mijn oude dag.",
    shortDescription: "Een kleine Chihuahua met een groot karakter die een rustig huisje zoekt.",
    imageUrl: "https://placedog.net/500/400?id=8",
    status: "beschikbaar",
    badge: "dringend",
    isFeatured: false,
    intakeDate: "2024-01-15",
  },
  {
    name: "Rocky",
    slug: "rocky",
    species: "hond",
    breed: "Berner Sennenhond x Husky x Malamute",
    gender: "reu",
    dateOfBirth: "2020-12-20",
    isNeutered: true,
    description:
      "Rocky is een stevige hond die op zoek is naar een ervaren baasje. Ik ben een kruising van Berner Sennenhond, Husky en Malamute - een indrukwekkende verschijning met een zacht hart. Ik ben gecastreerd en heb nood aan een baasje dat mij de structuur, beweging en liefde kan bieden die ik verdien. Met geduld en consequentie word ik de beste vriend die je je kan wensen.",
    shortDescription: "Een stevige kruising die een ervaren en liefdevol baasje zoekt.",
    imageUrl: "https://placedog.net/500/400?id=9",
    status: "beschikbaar",
    intakeDate: "2024-04-01",
  },
  {
    name: "Tim",
    slug: "tim",
    species: "hond",
    breed: "Mechelse Herder",
    gender: "reu",
    dateOfBirth: "2012-09-19",
    isNeutered: false,
    description:
      "Dit is misschien wel het moeilijkste verhaal dat ik ooit moet vertellen. Tim is mijn naam en ik ben een oudere Mechelse Herder die al veel heeft meegemaakt. Ik zoek een rustig huisje waar ik mijn laatste jaren in alle rust en liefde kan doorbrengen. Ik ben een brave hond die nood heeft aan stabiliteit en een warm mandje.",
    shortDescription: "Een oudere Mechelse Herder die een rustig en liefdevol thuis zoekt.",
    imageUrl: "https://placedog.net/500/400?id=10",
    status: "beschikbaar",
    badge: "dringend",
    intakeDate: "2023-12-01",
  },
  {
    name: "Vito",
    slug: "vito",
    species: "hond",
    breed: "Mechelse Herder x Duitse Herder",
    gender: "reu",
    dateOfBirth: "2022-05-02",
    isNeutered: false,
    description:
      "Een knappe en indrukwekkende hond. Hij heeft een sterk karakter. Vito is mijn naam en ik ben een kruising van Mechelse Herder en Duitse Herder. Ik ben jong, energiek en intelligent. Ik zoek een ervaren baasje dat mij kan uitdagen en begeleiden. Met de juiste training en socialisatie word ik een fantastische metgezel.",
    shortDescription: "Een knappe en indrukwekkende kruising met een sterk karakter.",
    imageUrl: "https://placedog.net/500/400?id=11",
    status: "beschikbaar",
    intakeDate: "2024-08-01",
  },
  {
    name: "Snow",
    slug: "snow",
    species: "hond",
    breed: "Siberische Husky",
    gender: "reu",
    dateOfBirth: "2024-10-02",
    isNeutered: true,
    description:
      "Snow en Ice zijn onafscheidelijk. Wij zijn twee prachtige Husky's die samen een nieuw thuis zoeken. Snow is de rustigere van ons twee en houdt ervan om te knuffelen na een lange wandeling. Wij zoeken een actief gezin dat ons samen kan houden en ons de ruimte en liefde kan geven die we verdienen.",
    shortDescription: "Een prachtige Husky die samen met Ice een nieuw thuis zoekt.",
    imageUrl: "https://placedog.net/500/400?id=12",
    status: "beschikbaar",
    badge: "nieuw",
    isFeatured: true,
    intakeDate: "2025-01-15",
  },
  {
    name: "Ice",
    slug: "ice",
    species: "hond",
    breed: "Siberische Husky",
    gender: "teef",
    dateOfBirth: "2024-12-05",
    isNeutered: false,
    description:
      "Ice en Snow zijn onafscheidelijk. Ik ben de speelsere van ons twee en hou ervan om te rennen en te spelen. Samen met Snow zoek ik een actief gezin dat ons de ruimte en beweging kan geven die we nodig hebben. We zijn sociale honden die goed overweg kunnen met andere honden.",
    shortDescription: "Een speelse Husky die samen met Snow onafscheidelijk is.",
    imageUrl: "https://placedog.net/500/400?id=13",
    status: "beschikbaar",
    badge: "nieuw",
    intakeDate: "2025-01-15",
  },
];

export const catSeeds: NewAnimal[] = [
  {
    name: "Luna",
    slug: "luna",
    species: "kat",
    breed: "Europese Korthaar",
    gender: "poes",
    dateOfBirth: "2023-04-10",
    isNeutered: true,
    description:
      "Luna is een rustige, lieve cyperse kat die graag in de buurt van haar baasje is. Ze is gesteriliseerd, gechipt en geregistreerd. Luna is ideaal voor een rustig gezin of een alleenstaande die op zoek is naar een trouwe metgezel. Ze houdt van knuffelen en rustig bij je op de bank liggen.",
    shortDescription: "Een rustige, lieve cyperse kat die graag in de buurt van haar baasje is.",
    imageUrl: "https://placekitten.com/500/400",
    status: "beschikbaar",
    isFeatured: true,
    intakeDate: "2024-10-01",
  },
  {
    name: "Simba",
    slug: "simba",
    species: "kat",
    breed: "Europese Korthaar",
    gender: "kater",
    dateOfBirth: "2024-06-15",
    isNeutered: true,
    description:
      "Simba is een prachtige rode kater, speels en avontuurlijk. Hij kan goed overweg met andere katten en is altijd in voor een spel. Simba is gecastreerd, gechipt en geregistreerd. Hij zoekt een gezin met eventueel andere katten waar hij zijn speelse karakter kwijt kan.",
    shortDescription: "Een prachtige rode kater, speels en avontuurlijk.",
    imageUrl: "https://placekitten.com/501/400",
    status: "beschikbaar",
    badge: "nieuw",
    isFeatured: true,
    intakeDate: "2025-01-05",
  },
  {
    name: "Nala",
    slug: "nala",
    species: "kat",
    breed: "Europese Korthaar",
    gender: "poes",
    dateOfBirth: "2022-08-20",
    isNeutered: true,
    description:
      "Nala is een schuchtere poes die even tijd nodig heeft om aan je te wennen, maar als ze je eenmaal vertrouwt, is ze de liefste kat die er bestaat. Ze is gesteriliseerd, gechipt en geregistreerd. Nala zoekt een rustig huisje zonder kleine kinderen.",
    shortDescription: "Een schuchtere poes die met geduld de liefste kat wordt.",
    imageUrl: "https://placekitten.com/502/400",
    status: "beschikbaar",
    intakeDate: "2024-09-15",
  },
  {
    name: "Felix",
    slug: "felix",
    species: "kat",
    breed: "Europese Korthaar",
    gender: "kater",
    dateOfBirth: "2021-03-01",
    isNeutered: true,
    description:
      "Felix is een zwart-witte kater met een stoer uiterlijk maar een zacht hartje. Hij is gecastreerd, gechipt en geregistreerd. Felix houdt van buiten rondsnuffelen en van lekker eten. Hij zoekt een huisje met tuin waar hij zijn avonturen kan beleven.",
    shortDescription: "Een zwart-witte kater met een stoer uiterlijk maar een zacht hartje.",
    imageUrl: "https://placekitten.com/503/400",
    status: "beschikbaar",
    intakeDate: "2024-07-01",
  },
  {
    name: "Minoes",
    slug: "minoes",
    species: "kat",
    breed: "Pers x Europese Korthaar",
    gender: "poes",
    dateOfBirth: "2020-11-12",
    isNeutered: true,
    description:
      "Minoes is een fluffy dame die dol is op aandacht. Ze is gesteriliseerd, gechipt en geregistreerd. Met haar zachte vacht en lieve karakter is ze de perfecte knuffelkat. Ze zoekt een huisje waar ze de koningin van het huis kan zijn.",
    shortDescription: "Een fluffy dame die dol is op aandacht en knuffelen.",
    imageUrl: "https://placekitten.com/504/400",
    status: "gereserveerd",
    badge: "gereserveerd",
    intakeDate: "2024-05-15",
  },
];

export const otherAnimalSeeds: NewAnimal[] = [
  {
    name: "Balthazar",
    slug: "balthazar",
    species: "ezel",
    breed: "Ezel",
    gender: "mannetje",
    dateOfBirth: "2018-05-01",
    isNeutered: true,
    description:
      "Balthazar is een lieve ezel die op de oude locatie aan Kerkveld verblijft. Hij is rustig, sociaal en houdt van aandacht. Balthazar zoekt een weide met een schuilplaats en liefst een ezelvriendje.",
    shortDescription: "Een lieve, rustige ezel die van aandacht houdt.",
    imageUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Donkey_1_arp_750px.jpg/440px-Donkey_1_arp_750px.jpg",
    status: "beschikbaar",
    intakeDate: "2023-01-01",
  },
];
