import type { NewAnimal } from "@/types";

// High-quality Wix image URLs from the old website
const WIX = "https://static.wixstatic.com/media";

export const dogSeeds: NewAnimal[] = [
  {
    name: "Vito",
    slug: "vito",
    species: "hond",
    breed: "Mechelse Herder x Duitse Herder",
    gender: "reu",
    dateOfBirth: "2022-05-02",
    isNeutered: false,
    description:
      "Een knappe en indrukwekkende hond. Hij heeft een sterk karakter. Vito is mijn naam en ik ben een kruising van Mechelse Herder en Duitse Herder. Ik ben jong, energiek en intelligent. Ik zoek een ervaren baasje dat mij kan uitdagen en begeleiden. Met de juiste training en socialisatie word ik een fantastische metgezel.",
    shortDescription: "Een knappe en indrukwekkende kruising met een sterk karakter.",
    imageUrl: `${WIX}/12c6b4_cd2649975be84f4eb228b69c1ede8484~mv2.jpg/v1/fill/w_800,h_800,al_c,q_80,enc_auto/12c6b4_cd2649975be84f4eb228b69c1ede8484~mv2.jpg`,
    status: "beschikbaar",
    isFeatured: true,
    intakeDate: "2024-08-01",
  },
  {
    name: "Rocky",
    slug: "rocky",
    species: "hond",
    breed: "Berner Sennenhond x Husky x Malamute",
    gender: "reu",
    dateOfBirth: "2020-12-20",
    isNeutered: true,
    description:
      "Rocky is een stevige hond die op zoek is naar een ervaren baasje. Ik ben een kruising van Berner Sennenhond, Husky en Malamute - een indrukwekkende verschijning met een zacht hart. Ik ben gecastreerd en heb nood aan een baasje dat mij de structuur, beweging en liefde kan bieden die ik verdien. Met geduld en consequentie word ik de beste vriend die je je kan wensen.",
    shortDescription: "Een stevige kruising die een ervaren en liefdevol baasje zoekt.",
    imageUrl: `${WIX}/12c6b4_fe290441b8a445b298236e8d171f04de~mv2.jpg/v1/fill/w_800,h_800,al_c,q_80,enc_auto/12c6b4_fe290441b8a445b298236e8d171f04de~mv2.jpg`,
    status: "beschikbaar",
    isFeatured: true,
    intakeDate: "2024-04-01",
  },
  {
    name: "Boy",
    slug: "boy",
    species: "hond",
    breed: "Engelse Pointer",
    gender: "reu",
    dateOfBirth: "2023-10-01",
    isNeutered: true,
    description:
      "Ik ben een jonge Engelse Pointer en ben via een inbeslagname in het asiel terechtgekomen. Boy is mijn naam en ik ben een echte gentleman. Ik ben gecastreerd, sociaal met andere honden en vol levenslust. Ik zoek een sportief baasje dat mij meeneemt op lange wandelingen en avonturen. Met de juiste begeleiding word ik de beste vriend die je je kan wensen.",
    shortDescription: "Een jonge Engelse Pointer vol levenslust en avontuur.",
    imageUrl: `${WIX}/12c6b4_71b76aeabafa44d6b1612132d897fa1f~mv2.jpeg/v1/fill/w_800,h_800,al_c,q_80,enc_auto/12c6b4_71b76aeabafa44d6b1612132d897fa1f~mv2.jpeg`,
    status: "beschikbaar",
    badge: "nieuw",
    isFeatured: true,
    intakeDate: "2025-01-10",
  },
  {
    name: "Athena",
    slug: "athena",
    species: "hond",
    breed: "Mechelse Herder",
    gender: "teef",
    dateOfBirth: "2022-03-09",
    isNeutered: false,
    description:
      "Ik ben een prachtige, compacte Mechelse herder van 3,5 jaar jong. Athena is mijn naam en ik ben even mooi als de godin naar wie ik vernoemd ben. Ik ben een actieve hond die nood heeft aan een ervaren baasje dat mij de structuur en de liefde kan geven die ik verdien. Ik ben intelligent, leergierig en wil niets liever dan mijn baasje trots maken.",
    shortDescription: "Een prachtige, compacte Mechelse herder van 3,5 jaar jong.",
    imageUrl: `${WIX}/12c6b4_8c5ac89ae40c41e09e8ab2998424c267~mv2.jpg/v1/fill/w_800,h_800,al_c,q_80,enc_auto/12c6b4_8c5ac89ae40c41e09e8ab2998424c267~mv2.jpg`,
    status: "beschikbaar",
    isFeatured: true,
    intakeDate: "2024-09-01",
  },
  {
    name: "Lex",
    slug: "lex",
    species: "hond",
    breed: "Siberische Husky",
    gender: "reu",
    dateOfBirth: "2020-09-15",
    isNeutered: true,
    description:
      "Een prachtige witte Husky, alsof ik recht uit een sneeuwlandschap ben gestapt. Lex is mijn naam en ik ben een echte schoonheid. Ik ben gecastreerd en klaar voor een nieuw leven. Ik hou van wandelen, rennen en spelen. Ik zoek een actief gezin met ervaring met Husky's die mij de beweging en aandacht kan geven die ik verdien.",
    shortDescription: "Een prachtige witte Husky, alsof hij recht uit een sneeuwlandschap komt.",
    imageUrl: `${WIX}/12c6b4_87a2ea0051c140629a19928739ae540c~mv2.jpg/v1/fill/w_800,h_800,al_c,q_80,enc_auto/12c6b4_87a2ea0051c140629a19928739ae540c~mv2.jpg`,
    status: "beschikbaar",
    intakeDate: "2024-05-01",
  },
  {
    name: "Tim",
    slug: "tim",
    species: "hond",
    breed: "Mechelse Herder",
    gender: "reu",
    dateOfBirth: "2012-09-19",
    isNeutered: false,
    description:
      "Dit is misschien wel het moeilijkste verhaal dat ik ooit moet vertellen. Tim is mijn naam en ik ben een oudere Mechelse Herder die al veel heeft meegemaakt. Ik zoek een rustig huisje waar ik mijn laatste jaren in alle rust en liefde kan doorbrengen. Ik ben een brave hond die nood heeft aan stabiliteit en een warm mandje.",
    shortDescription: "Een oudere Mechelse Herder die een rustig en liefdevol thuis zoekt.",
    imageUrl: `${WIX}/12c6b4_9df752ba213d4b938af938ed353ec26f~mv2.jpg/v1/fill/w_800,h_800,al_c,q_80,enc_auto/12c6b4_9df752ba213d4b938af938ed353ec26f~mv2.jpg`,
    status: "beschikbaar",
    badge: "dringend",
    intakeDate: "2023-12-01",
  },
  {
    name: "Bella",
    slug: "bella",
    species: "hond",
    breed: "Siberische Husky",
    gender: "teef",
    dateOfBirth: "2020-12-29",
    isNeutered: true,
    description:
      "En ja hoor, mijn naam zegt het al: ik ben mooi. Ik ben Bella, een prachtige Siberische Husky met de mooiste blauwe ogen die je ooit gezien hebt. Ik ben gesteriliseerd en klaar om een nieuw avontuur te beginnen. Ik hou van lange wandelingen, in de sneeuw spelen en knuffelen op de bank. Ik zoek een actief gezin dat mij de ruimte en beweging kan geven die ik nodig heb.",
    shortDescription: "Een prachtige Siberische Husky met de mooiste blauwe ogen.",
    imageUrl: `${WIX}/12c6b4_17a5e4e047244662b0538c4d4d146a75~mv2.jpg/v1/fill/w_800,h_800,al_c,q_80,enc_auto/12c6b4_17a5e4e047244662b0538c4d4d146a75~mv2.jpg`,
    status: "beschikbaar",
    isFeatured: true,
    intakeDate: "2024-03-15",
  },
  {
    name: "Iza",
    slug: "iza",
    species: "hond",
    breed: "American Staffordshire Terrier",
    gender: "teef",
    dateOfBirth: "2023-05-23",
    isNeutered: false,
    description:
      "Een jonge, lieve Stafford met een groot hart, een nog grotere knuffelnood en de liefste ogen die je ooit gezien hebt. Iza is mijn naam en ik wil niets liever dan bij mijn baasje op de bank liggen en geknuffeld worden. Ik ben vriendelijk, speels en altijd in voor een wandeling. Geef mij een kans en ik beloof je dat ik je leven zal verrijken met onvoorwaardelijke liefde.",
    shortDescription: "Een jonge, lieve Stafford met een groot hart en een nog grotere knuffelnood.",
    imageUrl: `${WIX}/12c6b4_000d3f0edc4740dfb2eda99be7f49537~mv2.jpg/v1/fill/w_800,h_800,al_c,q_80,enc_auto/12c6b4_000d3f0edc4740dfb2eda99be7f49537~mv2.jpg`,
    status: "beschikbaar",
    isFeatured: true,
    intakeDate: "2024-11-01",
  },
  {
    name: "Aira",
    slug: "aira",
    species: "hond",
    breed: "Terrier Mix",
    gender: "reu",
    dateOfBirth: "2015-03-15",
    isNeutered: true,
    description:
      "Officieel ben ik een oudere heer, maar noem mij gerust een jonge kerel. Ik ben Aira, een terrier mix met een hart van goud. Ondanks mijn leeftijd zit ik nog vol energie en ben ik altijd in voor een stevige wandeling of een gezellig spel. Ik ben op zoek naar een rustig huisje waar ik mijn oude dag kan doorbrengen met een baasje dat van mij houdt.",
    shortDescription: "Een lieve terrier mix die nog vol energie zit ondanks zijn leeftijd.",
    imageUrl: `${WIX}/12c6b4_82b5a4729ae842899aa54c1e5ee67b79~mv2.jpg/v1/fill/w_800,h_800,al_c,q_80,enc_auto/12c6b4_82b5a4729ae842899aa54c1e5ee67b79~mv2.jpg`,
    status: "beschikbaar",
    intakeDate: "2024-06-01",
  },
  {
    name: "Kamiel",
    slug: "kamiel",
    species: "hond",
    breed: "American Staffordshire Terrier",
    gender: "reu",
    dateOfBirth: "2021-06-01",
    isNeutered: true,
    description:
      "Ik ben in de opvang beland via de politie. Kamiel is mijn naam en ik ben een stevige American Stafford die op zoek is naar een ervaren baasje. Ik ben gecastreerd en heb een goed karakter, maar ik heb wel een baasje nodig dat mij begrijpt en mij de leiding geeft die ik nodig heb. Met de juiste begeleiding ben ik een trouwe en liefdevolle metgezel.",
    shortDescription: "Een stevige American Stafford op zoek naar een ervaren baasje.",
    imageUrl: `${WIX}/12c6b4_8f2450fd66ae447ea8198a373208a1c1~mv2.jpg/v1/fill/w_800,h_800,al_c,q_80,enc_auto/12c6b4_8f2450fd66ae447ea8198a373208a1c1~mv2.jpg`,
    status: "gereserveerd",
    badge: "gereserveerd",
    intakeDate: "2024-07-15",
  },
];

export const catSeeds: NewAnimal[] = [
  {
    name: "Tobias & Thor",
    slug: "tobias-en-thor",
    species: "kat",
    breed: "Europese Korthaar",
    gender: "kater",
    dateOfBirth: "2023-06-01",
    isNeutered: true,
    description:
      "Tobias en Thor zijn een onafscheidelijk duo. Deze twee broers doen alles samen: spelen, slapen en knuffelen. Ze zijn gecastreerd, gechipt en geregistreerd. Ze zoeken een gezin dat hen samen kan houden en hen de liefde en ruimte kan geven die ze verdienen.",
    shortDescription: "Een onafscheidelijk kattenduo dat samen een nieuw thuis zoekt.",
    imageUrl: `${WIX}/12c6b4_a9e7932650044215bbd9e40601ba6b22~mv2.jpg/v1/fill/w_800,h_800,al_c,q_80,enc_auto/12c6b4_a9e7932650044215bbd9e40601ba6b22~mv2.jpg`,
    status: "beschikbaar",
    isFeatured: true,
    intakeDate: "2024-10-01",
  },
  {
    name: "Molly",
    slug: "molly",
    species: "kat",
    breed: "Europese Korthaar",
    gender: "poes",
    dateOfBirth: "2022-04-15",
    isNeutered: true,
    description:
      "Molly is een lieve poes die op zoek is naar een rustig huisje. Ze is gesteriliseerd, gechipt en geregistreerd. Met wat geduld en liefde ontpopt ze zich tot de perfecte huiskat.",
    shortDescription: "Een lieve poes op zoek naar een rustig en liefdevol thuis.",
    imageUrl: `${WIX}/12c6b4_645effbfddb34c6286c5cd160bad282d~mv2.jpg/v1/fill/w_800,h_800,al_c,q_80,enc_auto/12c6b4_645effbfddb34c6286c5cd160bad282d~mv2.jpg`,
    status: "beschikbaar",
    isFeatured: true,
    intakeDate: "2024-09-15",
  },
  {
    name: "Dahlia",
    slug: "dahlia",
    species: "kat",
    breed: "Europese Korthaar",
    gender: "poes",
    dateOfBirth: "2023-03-01",
    isNeutered: true,
    description:
      "Dahlia is een prachtige poes met een zacht karakter. Ze is gesteriliseerd, gechipt en geregistreerd. Ze zoekt een huisje waar ze de koningin van het huis kan zijn.",
    shortDescription: "Een prachtige poes met een zacht karakter.",
    imageUrl: `${WIX}/12c6b4_4ad661738231484d951a64913fa39545~mv2.jpg/v1/fill/w_800,h_800,al_c,q_80,enc_auto/12c6b4_4ad661738231484d951a64913fa39545~mv2.jpg`,
    status: "beschikbaar",
    intakeDate: "2024-08-01",
  },
  {
    name: "Mina",
    slug: "mina",
    species: "kat",
    breed: "Europese Korthaar",
    gender: "poes",
    dateOfBirth: "2021-07-10",
    isNeutered: true,
    description:
      "Mina is een rustige, elegante poes die graag in de buurt van haar baasje is. Ze is gesteriliseerd, gechipt en geregistreerd. Mina is ideaal voor een rustig gezin of een alleenstaande die op zoek is naar een trouwe metgezel.",
    shortDescription: "Een rustige, elegante poes die graag in de buurt van haar baasje is.",
    imageUrl: `${WIX}/12c6b4_889dcf8209874d03820f683a6451b548~mv2.jpg/v1/fill/w_800,h_800,al_c,q_80,enc_auto/12c6b4_889dcf8209874d03820f683a6451b548~mv2.jpg`,
    status: "beschikbaar",
    intakeDate: "2024-07-01",
  },
];

export const otherAnimalSeeds: NewAnimal[] = [
  {
    name: "Joske",
    slug: "joske",
    species: "ander",
    breed: "Ezel",
    gender: "mannetje",
    dateOfBirth: "2018-05-01",
    isNeutered: false,
    description:
      "Joske is een lieve ezel die op de locatie aan Kerkveld verblijft. Hij is rustig, sociaal en houdt van aandacht. Joske zoekt een weide met een schuilplaats en liefst een ezelvriendje.",
    shortDescription: "Een lieve, rustige ezel die van aandacht houdt.",
    imageUrl: `${WIX}/12c6b4_bf89fa1f8c3249629b2948e416f46c6e~mv2.jpg/v1/fill/w_800,h_800,al_c,q_80,enc_auto/12c6b4_bf89fa1f8c3249629b2948e416f46c6e~mv2.jpg`,
    status: "beschikbaar",
    intakeDate: "2023-01-01",
  },
  {
    name: "Theo",
    slug: "theo",
    species: "ander",
    breed: "Hangbuikvarken",
    gender: "mannetje",
    dateOfBirth: "2020-03-01",
    isNeutered: true,
    description:
      "Theo is een gezellig hangbuikvarken dat op de Kerkveld-locatie verblijft. Hij is sociaal, nieuwsgierig en houdt van eten en knuffels. Theo zoekt een ruim buitenverblijf met een schuilplaats.",
    shortDescription: "Een gezellig hangbuikvarken dat van eten en knuffels houdt.",
    imageUrl: `${WIX}/12c6b4_adc6c63de5144e0aa5d1abcb2f16d9a9~mv2.jpg/v1/fill/w_800,h_800,al_c,q_80,enc_auto/12c6b4_adc6c63de5144e0aa5d1abcb2f16d9a9~mv2.jpg`,
    status: "beschikbaar",
    isFeatured: true,
    intakeDate: "2023-06-01",
  },
];
